update psycopg to 2.8.3
mainly because of
Error: could not determine PostgreSQL version from '11.4'
otherwise

note that we are not using psql 11 for our DB,
just the uwsgi/django container seems to have this
as the default psql client (now).